# tailscale's relay server
- name: configure dns for derp
  cloudflare_dns:
    api_token: "{{ CLOUDFLARE_API_TOKEN }}"
    zone: coherence.space # FIXME
    type: CNAME
    record: ts
    value: "{{ inventory_hostname }}"

- name: install derp
  pacman: name=derper state=present

- name: copy derp config file
  template: src=derper.conf.j2 dest=/etc/conf.d/derper mode=0644
  notify: restart derp

- name: start and enable derp
  service: name=derper.service enabled=yes state=started

- name: add caddy config
  template: src=derp.caddy.j2 dest=/etc/caddy/conf.d/derp.caddy mode=0644
  notify: reload caddy
