---

- name: update package cache
  pacman: update_cache=yes

- name: daemon reload
  systemd:
    daemon-reload: true

- name: restart sshd
  service: name=sshd state=restarted

- name: restart fail2ban
  systemd:
    name: fail2ban
    state: restarted

- name: reload firewalld
  systemd: name=firewalld state=reloaded
