---
- name: configure dns for dpb
  cloudflare_dns:
    api_token: "{{ CLOUDFLARE_API_TOKEN }}"
    zone: coherence.space
    type: CNAME
    record: paste
    value: "{{ inventory_hostname }}"

- name: create dpb directory
  file: path={{ item }} state=directory mode=0755
  loop:
    - /root/dpb-rs

- name: copy dpb configs
  template: src={{ item }}.j2 dest=/root/dpb-rs/{{ item }} mode=0644
  loop:
    - docker-compose.yml

- name: pull docker image
  command:
    chdir: /root/dpb-rs
    cmd: docker compose pull
  when: update is defined
  register: result
  changed_when: '"Pulling fs layer" in result.stderr'

- name: create and start service
  command:
    chdir: /root/dpb-rs
    cmd: docker compose up -d
  register: result
  changed_when: '"Starting" in result.stderr'

- name: add caddy config
  template: src=dpb.caddy.j2 dest=/etc/caddy/conf.d/dpb.caddy mode=0644
  notify: reload caddy
