---
- name: configure dns for prometheus
  cloudflare_dns:
    api_token: "{{ CLOUDFLARE_API_TOKEN }}"
    zone: coherence.space # FXIME
    type: CNAME
    record: prometheus
    value: "{{ inventory_hostname }}"

- name: configure dns for prometheus longterm
  cloudflare_dns:
    api_token: "{{ CLOUDFLARE_API_TOKEN }}"
    zone: coherence.space # FXIME
    type: CNAME
    record: prometheus-longterm
    value: "{{ inventory_hostname }}"

- name: configure dns for grafana
  cloudflare_dns:
    api_token: "{{ CLOUDFLARE_API_TOKEN }}"
    zone: coherence.space # FXIME
    type: CNAME
    record: grafana
    value: "{{ inventory_hostname }}"

- name: install prometheus and grafana
  pacman: name=prometheus,grafana state=present

- name: Create grafana provisioning directory
  file: path={{ item }} mode=0700 owner=grafana group=grafana state=directory
  with_items:
    - /etc/grafana/provisioning
    - /etc/grafana/provisioning/datasources
    - /etc/grafana/provisioning/dashboards
    - /etc/grafana/provisioning/plugins
    - /etc/grafana/provisioning/notifiers
    - /etc/grafana/provisioning/alerting
    - /etc/grafana/dashboards

- name: Install grafana datasources provisioning
  template: src=datasources.yaml.j2 dest=/etc/grafana/provisioning/datasources/datasources.yml owner=grafana group=grafana mode=0600
  notify: restart grafana

- name: Install grafana dashboards provisioning
  template: src=dashboards.yaml.j2 dest=/etc/grafana/provisioning/dashboards/dashboards.yml owner=grafana group=grafana mode=0600
  notify: restart grafana

- name: copy dashboards
  copy: src=dashboards/ dest=/etc/grafana/dashboards/ owner=grafana group=grafana mode=0644
  notify: restart grafana

- name: copy alerting config
  template: src=alerting/{{ item }}.j2 dest=/etc/grafana/provisioning/alerting/{{ item }} owner=grafana group=grafana mode=0644
  with_items:
    - contact_points.yaml
    - notification_policies.yaml
    - rules.yaml
  notify: restart grafana

- name: mkdir for prometheus-longterm database
  file: path=/var/lib/prometheus-longterm state=directory mode=0755 owner=prometheus group=prometheus

- name: copy prometheus-longterm config
  template: src=prometheus-longterm.yml.j2 dest=/etc/prometheus/prometheus-longterm.yml mode=0644
  notify: restart prometheus-longterm

- name: copy prometheus config
  template: src=prometheus.yml.j2 dest=/etc/prometheus/prometheus.yml mode=0644
  notify: restart prometheus

- name: validate prometheus config
  ansible.builtin.command: promtool check config /etc/prometheus/{{ item }}.yml
  loop:
    - prometheus
    - prometheus-longterm
  register: result
  changed_when: result.rc != 0

- name: copy grafana config
  template: src=grafana.ini.j2 dest=/etc/grafana.ini mode=0644
  notify: restart grafana

- name: copy caddy config
  template: src={{ item }}.j2 dest=/etc/caddy/conf.d/{{ item }} mode=0644
  loop:
    - prometheus.caddy
    - grafana.caddy
  notify: reload caddy

- name: Install prometheus-longterm service
  template: src=prometheus-longterm.service.j2 dest=/etc/systemd/system/prometheus-longterm.service owner=root group=root mode=0644
  notify: restart prometheus-longterm

- name: start and enable prometheus-longterm
  service: name=prometheus-longterm.service enabled=yes state=started

- name: start and enable prometheus
  service: name=prometheus.service enabled=yes state=started

- name: start and enable grafana
  service: name=grafana.service enabled=yes state=started
