---
# See also: https://github.com/artis3n/ansible-role-tailscale/blob/main/tasks/install.yml

- name: Install tailscale
  pacman: name=tailscale state=present

- name: Enable service
  systemd: name=tailscaled state=started enabled=true

# https://tailscale.com/kb/1103/exit-nodes
- name: add firewalld rule to make exit node work
  command: firewall-cmd --permanent --add-masquerade
  notify:
    - reload firewalld

- name: Check if Tailscale is connected
  ansible.builtin.command: tailscale status --json
  changed_when: false
  register: tailscale_status
  failed_when:
    - tailscale_status.rc != 0

- name: Parse status JSON
  vars:
    tailscale_status_parsed: "{{ tailscale_status.stdout | from_json }}"
  ansible.builtin.set_fact:
    tailscale_is_online: "{{  tailscale_status_parsed.Self.Online }}"

- name: Bring Tailscale Up
  ansible.builtin.command: tailscale up --authkey={{ tailscale_authkey }} --advertise-exit-node
  when: not tailscale_is_online
  notify: Confirm Tailscale is Connected

- name: Set firewalld rules
  command: firewall-cmd --permanent --zone=trusted --add-interface=tailscale0
  register: firewalld_status
  changed_when: '"ALREADY_ENABLED" not in firewalld_status.stderr'
  notify:
    - reload firewalld

# Note: roles/arch_common/tasks/main.yml also has some tailscale configs
