---

- name: install gitea
  pacman: name=gitea state=present

- name: copy gitea config file
  template: src=app.ini.j2 dest=/etc/gitea/app.ini mode=0644 user=gitea group=gitea
  notify: restart gitea

- name: start and enable gitea
  service: name=gitea.service enabled=yes state=started

- name: add caddy config
  template: src=gitea.caddy.j2 dest=/etc/caddy/conf.d/gitea.caddy mode=0644
  notify: reload caddy
