---
- name: install shadowsocks
  pacman: name=shadowsocks-rust-git state=present

- name: copy kernel config file
  copy: src=99-sysctl.conf dest=/etc/sysctl.d/ mode=644
  register: copy_config_res

# as per: https://shadowsocks.org/en/config/advanced.html
- name: apply kernel parameters
  command: sysctl --system
  when: copy_config_res.changed

- name: create shadowsocks config dir
  file: path=/etc/shadowsocks-rust/ state=directory mode=0755

- name: copy shadowsocks config
  template: src=config.json.j2 dest=/etc/shadowsocks-rust/config.json mode=0644

- name: start and enable shadowsocks-server
  service: name=shadowsocks-rust-server@config.service enabled=yes state=started
