---

- name: create data directory
  file: path=/var/www/beian state=directory mode=0755 owner=caddy group=caddy

- name: copy html
  template: src=index.html.j2 dest=/var/www/beian/index.html mode=0644 owner=caddy group=caddy

- name: add caddy config
  template: src=beian.caddy.j2 dest=/etc/caddy/conf.d/beian.caddy mode=0644
  notify: reload caddy
