{
 "title": "esp32",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "esphome_sensor_value{type=\"temperature\"}",
     "legendFormat": "{{room}}"
    }
   ]
  },
  {
   "title": "Signal",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dBm" } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=\"pvvx_signal\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "esphome_sensor_value{type=\"humidity\"}",
     "legendFormat": "{{room}}"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "esphome_sensor_value{id=\"pvvx_battery-voltage\"}",
     "legendFormat": "{{id}}"
    },
    {
     "expr": "esphome_sensor_value{type=\"battery\"}",
     "legendFormat": "{{room}}"
    }
   ]
  }
 ]
}