---
# This role is currently for a reverse proxy for telegram bot api.
# In the future, there may be more reverse proxies to be added in this role.
- name: add caddy config
  template: src=reverse_proxy.caddy.j2 dest=/etc/caddy/conf.d/reverse_proxy.caddy mode=0644
  notify: reload caddy
