---

- name: configure dns
  cloudflare_dns:
    api_token: "{{ CLOUDFLARE_API_TOKEN }}"
    zone: "{{ zone }}"
    type: CNAME
    record: "{{ domain }}"
    value: "{{ ansible_fqdn }}"

- name: create data directory
  file: path=/root/plausible_analytics state=directory mode=0755

- name: copy plausible_analytics configs
  template: src={{ item }}.j2 dest=/root/plausible_analytics/{{ item }} mode=0644
  with_items:
    - docker-compose.yml
    - clickhouse-config.xml
    - clickhouse-user-config.xml
    - plausible-conf.env

- name: create and start service
  docker_compose:
    state: present
    project_src: /root/plausible_analytics
    pull: "{{ update is defined }}"

- name: add caddy config
  template: src=plausible_analytics.caddy.j2 dest=/etc/caddy/conf.d/plausible_analytics.caddy mode=0644
  notify: reload caddy
