---
- name: restart prometheus
  service: name=prometheus.service state=restarted

- name: restart grafana
  service: name=grafana.service state=restarted

- name: restart prometheus-longterm
  service: name=prometheus-longterm.service state=restarted
