---
- name: configure dns for miniflus
  cloudflare_dns:
    api_token: "{{ CLOUDFLARE_API_TOKEN }}"
    zone: coherence.space
    type: CNAME
    record: rss
    value: "{{ inventory_hostname }}"

- name: create data directory
  file: path=/root/miniflux state=directory mode=0755

- name: copy miniflux docker-compose.yml
  template: src=docker-compose.yml.j2 dest=/root/miniflux/docker-compose.yml mode=0644

- name: pull docker image
  command:
    chdir: /root/miniflux
    cmd: docker compose pull
  when: update is defined
  register: result
  changed_when: '"Pulling fs layer" in result.stderr'

- name: create and start service
  command:
    chdir: /root/miniflux
    cmd: docker compose up -d
  register: result
  changed_when: '"Starting" in result.stderr'

- name: add caddy config
  template: src=miniflux.caddy.j2 dest=/etc/caddy/conf.d/miniflux.caddy mode=0644
  notify: reload caddy
