---

- name: setup beijing tencent
  hosts: beijing
  roles:
    - { role: arch_common, china_mirror: yes}
    - frps
    - { role: caddy, tags: [caddy] }
    - { role: miniflux, tags: [miniflux] }
    - { role: beian, tags: [beian] }
