---

- name: setup beijing tencent
  hosts: beijing
  roles:
    - { role: arch_common, china_mirror: yes}
    - frps
    - { role: caddy, tags: [caddy] }
    - { role: miniflux, tags: [miniflux] }
    - { role: beian, tags: [beian] }
    - rsshub
    - { role: dpb, tags: [dpb] }
    - { role: syncthing, tags: [syncthing] }
    - { role: fava, tags: [fava] }
    - { role: gitea, tags: [gitea] }
    - role: plausible_analytics
      vars: { zone: coherence.space, domain: analytics }
      tags: [pa]
