---

- name: Setup beijing tencent
  hosts: beijing
  roles:
    - { role: arch_common, china_mirror: true}
    - frps
    - { role: caddy, tags: [caddy] }
    - { role: miniflux, tags: [miniflux] }
    - { role: beian, tags: [beian] }
    - { role: rsshub, tags: [rsshub]}
    - { role: dpb, tags: [dpb] }
    - { role: syncthing, tags: [syncthing] }
    - { role: fava, tags: [fava] }
    - { role: gitea, tags: [gitea] }
    - role: plausible_analytics
      vars: { zone: coherence.space, domain: analytics }
      tags: [pa]
    - { role: authelia, tags: [authelia] }
    - { role: monitoring_exporter, tags: [monitoring_exporter] }
