---
- name: configure dns for docker registry
  cloudflare_dns:
    api_token: "{{ CLOUDFLARE_API_TOKEN }}"
    zone: coherence.codes
    type: CNAME
    record: docker
    value: "{{ inventory_hostname }}"

- name: create data directory
  file: path={{ item }} state=directory mode=0755
  loop:
    - /root/docker-registry

- name: copy docker-compose.yml
  template: src=docker-compose.yaml.j2 dest=/root/docker-registry/docker-compose.yml mode=0644

- name: copy configs
  template: src={{ item }}.j2 dest=/root/docker-registry/{{ item }} mode=0644
  loop:
    - config.yaml
  notify: restart service

- name: pull docker image
  command:
    chdir: /root/docker-registry
    cmd: docker compose pull
  when: update is defined
  register: result
  changed_when: '"Pulling fs layer" in result.stderr'

- name: create and start service
  command:
    chdir: /root/docker-registry
    cmd: docker compose up -d
  register: result
  changed_when: '"Starting" in result.stderr'

- name: add caddy config
  template: src=docker-registry.caddy.j2 dest=/etc/caddy/conf.d/docker-registry.caddy mode=0644
  notify: reload caddy
